"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, LogOut, Loader2, Plus, RefreshCw, Search, ShieldCheck, UserRound } from "lucide-react";
import { formatDateAr, formatTimeAr, todayCairo } from "@/lib/time";
import type { AppointmentDTO, DepartmentDTO, DoctorDTO } from "@/lib/types";
import { STATUS_LABELS } from "@/lib/types";

type Slot = { time: string; booked: boolean };
const statusStyle: Record<string, string> = { confirmed: "bg-mint text-teal-deep", checked_in: "bg-gold/25 text-teal-dark", completed: "bg-teal text-white", no_show: "bg-ink/10 text-ink/60" };

export default function ReceptionApp() {
  const [authed, setAuthed] = useState<boolean | null>(null), [password, setPassword] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [apps, setApps] = useState<AppointmentDTO[]>([]), [depts, setDepts] = useState<DepartmentDTO[]>([]), [docs, setDocs] = useState<DoctorDTO[]>([]);
  const [date, setDate] = useState(todayCairo()), [deptId, setDeptId] = useState(""), [doctorId, setDoctorId] = useState(""), [search, setSearch] = useState(""), [loading, setLoading] = useState(false);
  const [showAdd, setShowAdd] = useState(false), [moving, setMoving] = useState<number | null>(null), [message, setMessage] = useState("");
  const [form, setForm] = useState({ doctorId: "", date: todayCairo(), time: "", patientName: "", phone: "", address: "", age: "", visitType: "new", notes: "" });
  const [slots, setSlots] = useState<Slot[]>([]), [moveForm, setMoveForm] = useState({ doctorId: "", date: todayCairo(), time: "" }), [moveSlots, setMoveSlots] = useState<Slot[]>([]);

  useEffect(() => { fetch("/api/reception/logout", { method: "POST" }).finally(() => setAuthed(false)); }, []);
  const login = async () => { setBusy(true); setError(""); const r = await fetch("/api/reception/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const d = await r.json().catch(() => ({})); if (r.ok) setAuthed(true); else { setError(d.message || "كلمة المرور غير صحيحة"); setPassword(""); } setBusy(false); };
  const loadCatalog = async () => { const r = await fetch("/api/reception/catalog"); const d = await r.json(); if (d.ok) { setDepts(d.departments || []); setDocs(d.doctors || []); } };
  const loadApps = async () => { setLoading(true); const q = new URLSearchParams({ date }); if (deptId) q.set("departmentId", deptId); if (doctorId) q.set("doctorId", doctorId); const r = await fetch(`/api/reception/appointments?${q}`); const d = await r.json(); if (d.ok) setApps(d.appointments || []); setLoading(false); };
  useEffect(() => { if (authed) { loadCatalog(); loadApps(); } }, [authed]);
  useEffect(() => { if (authed) loadApps(); }, [date, deptId, doctorId]);
  const filteredDocs = useMemo(() => deptId ? docs.filter((d) => String(d.departmentId) === deptId) : docs, [docs, deptId]);
  const visible = apps.filter((a) => !search || `${a.patientName} ${a.phone} ${a.refCode}`.toLowerCase().includes(search.toLowerCase()));
  const fetchSlots = async (doc: string, day: string, setter: (v: Slot[]) => void) => { if (!doc || !day) { setter([]); return; } const r = await fetch(`/api/slots?doctorId=${doc}&date=${day}`); const d = await r.json(); setter(d.ok ? (d.slots || []).filter((s: Slot) => !s.booked) : []); };
  const add = async () => { setBusy(true); setMessage(""); const r = await fetch("/api/reception/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (r.ok) { setMessage(`تم إنشاء الحجز ${d.appointment?.refCode || ""}`); setShowAdd(false); setForm({ doctorId: "", date: todayCairo(), time: "", patientName: "", phone: "", address: "", age: "", visitType: "new", notes: "" }); await loadApps(); } else setMessage(d.message || "تعذر إنشاء الحجز"); setBusy(false); };
  const status = async (id: number, value: string) => { await fetch(`/api/reception/appointments/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value }) }); loadApps(); };
  const move = async (id: number) => { setBusy(true); const r = await fetch(`/api/reception/appointments/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(moveForm) }); const d = await r.json(); setMessage(r.ok ? "تم نقل الحجز بنجاح" : (d.message || "تعذر نقل الحجز")); if (r.ok) { setMoving(null); loadApps(); } setBusy(false); };

  if (authed === null) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="animate-spin text-teal" size={40} /></div>;
  if (!authed) return <div className="mx-auto max-w-md pt-6"><div className="rounded-[2.5rem] bg-teal-dark p-8 text-center shadow-2xl sm:p-10"><span className="mx-auto mb-5 grid size-16 place-items-center rounded-3xl bg-gold text-teal-dark"><ShieldCheck size={28} /></span><h1 className="font-display text-2xl font-black text-white">صفحة الاستقبال</h1><p className="mt-2 text-sm text-cream/70">دخول مخصص لمتابعة الحجوزات وإضافة حجز يدوي</p><input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && login()} placeholder="كلمة مرور الاستقبال" className="mt-7 w-full rounded-2xl border-2 border-white/15 bg-white/10 px-5 py-4 text-center text-lg text-white outline-none focus:border-gold" />{error && <p className="mt-3 rounded-xl bg-rose-500/20 p-2 text-sm font-bold text-rose-100">{error}</p>}<button onClick={login} disabled={busy || password.length < 4} className="mt-5 w-full rounded-2xl bg-gold px-5 py-4 font-extrabold text-teal-dark disabled:opacity-50">{busy ? <Loader2 className="mx-auto animate-spin" /> : "دخول"}</button></div></div>;

  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-2xl font-black text-teal-dark">لوحة الاستقبال</h1><p className="mt-1 text-xs font-bold text-ink-soft">متابعة كل الأقسام والأطباء والحجوزات اليدوية</p></div><div className="flex gap-2"><button onClick={() => setShowAdd((v) => !v)} className="inline-flex items-center gap-2 rounded-xl bg-teal-deep px-4 py-2.5 text-xs font-extrabold text-white"><Plus size={15} /> حجز يدوي</button><button onClick={async () => { await fetch("/api/reception/logout", { method: "POST" }); setAuthed(false); }} className="inline-flex items-center gap-2 rounded-xl border border-rose-soft/30 px-4 py-2.5 text-xs font-extrabold text-rose-soft"><LogOut size={15} /> خروج</button></div></div>
    {message && <div className="rounded-2xl bg-gold/20 px-4 py-3 text-sm font-extrabold text-teal-dark">{message}</div>}
    {showAdd && <section className="rounded-3xl border border-teal/10 bg-white p-5 shadow-sm"><h2 className="font-display text-lg font-black text-teal-dark">إضافة حجز يدوي</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><select className="field" value={form.doctorId} onChange={(e) => { const v = e.target.value; setForm({ ...form, doctorId: v, time: "" }); fetchSlots(v, form.date, setSlots); }}><option value="">اختر الطبيب</option>{docs.map((d) => <option key={d.id} value={d.id}>{d.name} — {d.departmentName}</option>)}</select><input type="date" className="field" value={form.date} onChange={(e) => { setForm({ ...form, date: e.target.value, time: "" }); fetchSlots(form.doctorId, e.target.value, setSlots); }} /><select className="field" value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })}><option value="">اختر الموعد المتاح</option>{slots.map((s) => <option key={s.time} value={s.time}>{formatTimeAr(s.time)}</option>)}</select><input className="field" placeholder="اسم المريض بالكامل" value={form.patientName} onChange={(e) => setForm({ ...form, patientName: e.target.value })} /><input className="field" dir="ltr" placeholder="رقم الهاتف" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input className="field" placeholder="السن" type="number" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} /><input className="field sm:col-span-2" placeholder="العنوان" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /><select className="field" value={form.visitType} onChange={(e) => setForm({ ...form, visitType: e.target.value })}><option value="new">كشف</option><option value="followup">إعادة</option></select><input className="field sm:col-span-3" placeholder="ملاحظات اختيارية" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><button onClick={add} disabled={busy} className="mt-4 rounded-xl bg-gold px-6 py-3 text-sm font-extrabold text-teal-dark disabled:opacity-50">{busy ? "جارٍ الحفظ..." : "تأكيد الحجز"}</button></section>}
    <div className="grid gap-3 rounded-3xl border border-teal/10 bg-white p-4 shadow-sm sm:grid-cols-4"><input type="date" className="field" value={date} onChange={(e) => setDate(e.target.value)} /><select className="field" value={deptId} onChange={(e) => { setDeptId(e.target.value); setDoctorId(""); }}><option value="">كل الأقسام</option>{depts.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><select className="field" value={doctorId} onChange={(e) => setDoctorId(e.target.value)}><option value="">كل الأطباء</option>{filteredDocs.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><div className="relative"><Search className="absolute right-3 top-3 text-ink-soft" size={16} /><input className="field pr-10" placeholder="بحث بالاسم أو الهاتف أو الكود" value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    <div className="flex items-center justify-between"><p className="text-xs font-extrabold text-ink-soft">{visible.length} حجز في القائمة</p><button onClick={loadApps} className="inline-flex items-center gap-2 rounded-xl border border-teal/20 bg-white px-3 py-2 text-xs font-extrabold text-teal"><RefreshCw size={14} className={loading ? "animate-spin" : ""} /> تحديث</button></div>
    {loading ? <div className="grid place-items-center rounded-3xl bg-white p-12"><Loader2 className="animate-spin text-teal" /></div> : visible.length === 0 ? <div className="rounded-3xl border border-dashed border-teal/25 bg-white p-12 text-center font-bold text-ink-soft">لا توجد حجوزات لهذا اليوم</div> : <div className="space-y-3">{visible.map((a) => <div key={a.id} className="rounded-3xl border border-teal/10 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center gap-3"><div className="grid size-14 place-items-center rounded-2xl bg-teal-dark text-center text-gold-light"><b>{formatTimeAr(a.time).split(" ")[0]}</b><small>{formatTimeAr(a.time).split(" ")[1]}</small></div><div className="min-w-[220px] flex-1"><p className="font-extrabold text-teal-dark"><UserRound size={14} className="ml-1 inline" />{a.patientName} <span className="mr-2 text-xs text-teal">{a.refCode}</span></p><p className="mt-1 text-xs font-bold text-ink-soft">{a.doctorName} — {a.departmentName} · <span dir="ltr">{a.phone}</span> · {a.age} سنة</p><p className="mt-1 text-[11px] font-bold text-ink-soft"><CalendarDays size={12} className="ml-1 inline" />{formatDateAr(a.date)}</p></div><select value={a.status} onChange={(e) => status(a.id, e.target.value)} className={`rounded-xl border-0 px-3 py-2 text-xs font-extrabold ${statusStyle[a.status]}`}>{Object.keys(STATUS_LABELS).map((s) => <option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select><button onClick={() => { setMoving(a.id); setMoveForm({ doctorId: String(a.doctorId), date: a.date, time: "" }); fetchSlots(String(a.doctorId), a.date, setMoveSlots); }} className="rounded-xl border border-teal/20 px-3 py-2 text-xs font-extrabold text-teal">نقل لطبيب/موعد</button></div>{moving === a.id && <div className="mt-3 grid gap-2 border-t border-dashed border-teal/15 pt-3 sm:grid-cols-3"><select className="field" value={moveForm.doctorId} onChange={(e) => { setMoveForm({ ...moveForm, doctorId: e.target.value, time: "" }); fetchSlots(e.target.value, moveForm.date, setMoveSlots); }}>{docs.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select><input type="date" className="field" value={moveForm.date} onChange={(e) => { setMoveForm({ ...moveForm, date: e.target.value, time: "" }); fetchSlots(moveForm.doctorId, e.target.value, setMoveSlots); }} /><select className="field" value={moveForm.time} onChange={(e) => setMoveForm({ ...moveForm, time: e.target.value })}><option value="">اختر الموعد</option>{moveSlots.map((s) => <option key={s.time} value={s.time}>{formatTimeAr(s.time)}</option>)}</select><div className="flex gap-2 sm:col-span-3"><button onClick={() => move(a.id)} disabled={busy || !moveForm.time} className="rounded-xl bg-gold px-4 py-2 text-xs font-extrabold text-teal-dark">تأكيد النقل</button><button onClick={() => setMoving(null)} className="rounded-xl border px-4 py-2 text-xs font-extrabold">إلغاء</button></div></div>}</div>)}</div>}
  </div>;
}
